### ISSUE TITLE
Reconnecting Sessions

### ISSUE THREAD

**Issue by bitmanip** [heshiming/ibga#10]
Is there a way to reconnect sessions when other logins are detected? It would be ideal if the gateway session would always take back control. Maybe a configuration option?

<img width="691" alt="Screenshot 2024-01-09 at 10 27 49 AM" src="https://github.com/heshiming/ibga/assets/3829978/d47ef73c-6458-499a-a05e-81e09811017a">

**Comment by heshiming** [comment]
Automatically clicking this button would make IBG compete with your other sessions. You are aware of the session when you log into the other software, supposedly trying to do something manually.

Do you want IBG to steal that session? Or do you want to wait for a few minutes before doing so?

**Comment by bitmanip** [comment]
Yes. I am aware. Ideally I would like IBG to disconnect any other sessions and always be the primary gateway. I need to keep it connected to the market at all times and this seems like a potential risk.

**Comment by heshiming** [comment]
Ok, sounds like you have deployed a system, which I admire. I'll make this an option soon and let you know via this thread.

**Comment by heshiming** [comment]
Hi, I just noticed that your message is on the initial startup of IBG, not in the middle. So in the [latest update](https://github.com/heshiming/ibga/commit/56caf3f7e5598c680a0b832fda85c386af2ac288), I decided to make it mandatory and default to kick out the existing session upon start. But it'll kick session just once.

I have updated the docker image, so if you pull now, it'll include the change.

**Comment by bitmanip** [comment]
Thanks a bunch. This is an excellent change. Really appreciate the help, and yes, I have deployed a system that is actively trading.
