### ISSUE TITLE
More recent docker images

### ISSUE THREAD

**Issue by atisharma** [heshiming/ibga#11]
Support for the openjdk docker images is [being dropped](https://hub.docker.com/_/openjdk) and debian bullseye is now 'oldstable'. Do you have plans to move to debian bookworm and a supported openjdk image provider?

**Comment by heshiming** [comment]
Thanks for the heads up. I'll find some time to move over to a debian base image.

**Comment by heshiming** [comment]
Sorry for the delay, in today's update, I upgraded the running base image to debian-bookworm and replaced jauto builder image openjdk with eclipse-temurin:22-jammy (ubuntu equivalent).
