### ISSUE TITLE
Use stable version of gateway instead of latest

### ISSUE THREAD

**Issue by kayazinc** [heshiming/ibga#6]
```
 IB Gateway Installation 1
----------------------------
• will install into /home/ibg
• will use the existing installer: /home/ibg/ibgateway-latest-standalone-linux-x64.sh ...
• installing ...
```
From the docker log, it seem that IBGA download and install the latest version of ibgateway.  May i suggest to use the stable version instead?

The benefits of stable version are:
* it doesn't need to auto-upgrade frequently
* its less prone to bugs (users feedback that v10.12 having market data issue)

**Comment by heshiming** [comment]
I'm with IBKR long enough to remember a "stable version" offer. However, I think they have phased that out, probably during the Log4J fiasco. Right now, if you go to their website and click "Download IB Gateway", no stable version is offered.

**Comment by heshiming** [comment]
I understand that's a googled page. It's not linked from IBKR's website. Or did you find one?

Yes I could've allowed changes from 'latest' to 'stable'. However, I hope not to spend extra time for something already phased out. There has to be a reason they are not linking to this 'stable version' from their website. It might not be working.

**Comment by heshiming** [comment]
So how did you get to https://www.interactivebrokers.com/en/index.php?f=16457&ns=T ? Where is this page linked from the website?

To me, I go to www.ibkr.com, click "Log In" at top-right, then click "Download IB Gateway". It leads me to the "latest" version. I found no link to a "stable" version there.

**Comment by heshiming** [comment]
Exactly! I remember having dual download options on that page before. The stable version was removed and it has to be intentional.

**Comment by heshiming** [comment]
With the latest update, you can use the following environment variable in a docker-compose service node to point to the stable version:

    environment:
      - IBG_DOWNLOAD_URL=https://download2.interactivebrokers.com/installers/ibgateway/stable-standalone/ibgateway-stable-standalone-linux-x64.sh
