### ISSUE TITLE
IBGA requires 12gb of virtual memory?

### ISSUE THREAD

**Issue by kayazinc** [heshiming/ibga#8]
```
 71392 2000      20   0   12.1g 813464  57960 S   3.0   2.5   0:34.01 java
```
From `top`, it shown that IBGA requires 12gb of virtual memory.  Is it normal or is it be due to my misconfiguration of the docker?

Thanks!

**Comment by heshiming** [comment]
Virtual memory is probably not the best indicator of memory usage. A better one would be resident memory or "resident set size". [This serverfault question](https://serverfault.com/questions/138427/what-does-virtual-memory-size-in-top-mean) explains a bit about what virtual memory is.

Although I'm pretty sure IBGA is as slim as possible. No parts in IBGA runs on Java. IB Gateway, however, is a heavy Java program.
